import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

export default async function ReportDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect(`/auth?next=${encodeURIComponent(`/reports/${id}`)}`)
  const { data: complaint } = await supabase.from('complaints').select('id, public_id, title, description, status, priority, is_anonymous, created_at, updated_at, locations(name), categories(name), complaint_media(id, storage_path, media_type), complaint_history(id, from_status, to_status, note, created_at)').eq('id', id).eq('reporter_id', user.id).maybeSingle()
  if (!complaint) notFound()
  return <main className="min-h-screen bg-background px-6 py-10 text-foreground"><div className="mx-auto max-w-3xl"><Link href="/reports" className="font-mono text-xs font-bold tracking-[0.16em] text-primary">← My reports</Link><article className="mt-8 rounded-3xl border border-border bg-card p-6 sm:p-9"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="font-mono text-xs font-bold text-brand-blue">{complaint.public_id}</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-primary">{complaint.title}</h1></div><span className="h-fit rounded-full bg-brand-green-soft px-3 py-1.5 text-sm font-bold capitalize text-primary">{complaint.status.replaceAll('_', ' ')}</span></div><p className="mt-6 whitespace-pre-wrap leading-7 text-muted-foreground">{complaint.description}</p><div className="mt-8 grid gap-4 border-y border-border py-5 text-sm sm:grid-cols-3"><div><p className="text-muted-foreground">Priority</p><p className="mt-1 font-semibold capitalize text-primary">{complaint.priority}</p></div><div><p className="text-muted-foreground">Category</p><p className="mt-1 font-semibold text-primary">{complaint.categories?.name ?? 'Uncategorized'}</p></div><div><p className="text-muted-foreground">Location</p><p className="mt-1 font-semibold text-primary">{complaint.locations?.name ?? 'Not set'}</p></div></div><section className="mt-8"><h2 className="text-lg font-bold text-primary">Status history</h2><div className="mt-4 space-y-4">{complaint.complaint_history?.length ? complaint.complaint_history.sort((a,b) => a.created_at.localeCompare(b.created_at)).map((event) => <div key={event.id} className="border-l-2 border-brand-blue/30 pl-4"><p className="font-semibold capitalize text-primary">{event.to_status.replaceAll('_', ' ')}</p><p className="mt-1 text-sm text-muted-foreground">{event.note ?? 'Status updated'} · {new Date(event.created_at).toLocaleString()}</p></div>) : <p className="text-sm text-muted-foreground">Your report has been submitted and is waiting for review.</p>}</div></section></article></div></main>
}
