import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

export default async function ReportsPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/auth?next=/reports')
  const { data: complaints } = await supabase.from('complaints').select('id, public_id, title, description, status, priority, is_anonymous, created_at, locations(name), categories(name)').eq('reporter_id', user.id).order('created_at', { ascending: false })
  return <main className="min-h-screen bg-background px-6 py-10 text-foreground"><div className="mx-auto max-w-5xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><Link href="/" className="font-mono text-xs font-bold tracking-[0.16em] text-primary">REPORT<span className="text-brand-green">ANDFIX</span></Link><p className="mt-8 font-mono text-xs uppercase tracking-[0.18em] text-brand-blue">Reporter workspace</p><h1 className="mt-2 text-4xl font-bold tracking-tight text-primary">My reports</h1><p className="mt-2 text-muted-foreground">Track every issue you have submitted.</p></div><Link href="/" className="rounded-xl border border-border px-4 py-2 text-sm font-semibold hover:bg-muted">Back home</Link></div><div className="mt-8 space-y-4">{(complaints ?? []).length === 0 ? <div className="rounded-2xl border border-dashed border-border bg-card p-8 text-center"><h2 className="font-semibold text-primary">No reports yet</h2><p className="mt-2 text-sm text-muted-foreground">Scan an active campus QR code to submit your first report.</p></div> : complaints?.map((complaint) => <Link key={complaint.id} href={`/reports/${complaint.id}`} className="block rounded-2xl border border-border bg-card p-5 transition hover:border-brand-blue/50 hover:shadow-sm"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="font-mono text-xs font-bold text-brand-blue">{complaint.public_id}</p><h2 className="mt-1 text-xl font-bold text-primary">{complaint.title}</h2><p className="mt-2 line-clamp-2 text-sm text-muted-foreground">{complaint.description}</p></div><span className="h-fit rounded-full bg-brand-green-soft px-3 py-1 text-xs font-bold capitalize text-primary">{complaint.status.replaceAll('_', ' ')}</span></div><div className="mt-4 flex flex-wrap gap-3 text-xs text-muted-foreground"><span>{complaint.categories?.name ?? 'Uncategorized'}</span><span>·</span><span>{complaint.locations?.name ?? 'Location not set'}</span><span>·</span><span>{new Date(complaint.created_at).toLocaleDateString()}</span></div></Link>)}</div></div></main>
}
