'use client'

import { FormEvent, useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Props = { role: string; colleges: { id: string; name: string }[] }
type Staff = { id: string; full_name: string; role: string; is_suspended: boolean; college_id: string }

export default function StaffClient({ role, colleges }: Props) {
  const supabase = createClient()
  const [staff, setStaff] = useState<Staff[]>([])
  const [message, setMessage] = useState('')
  const [form, setForm] = useState({ fullName: '', email: '', password: '', role: 'worker', collegeId: colleges[0]?.id ?? '' })
  const load = async () => { const { data } = await supabase.rpc('staff_directory'); setStaff(data ?? []) }
  useEffect(() => { void load() }, [])
  async function createStaff(event: FormEvent) { event.preventDefault(); setMessage('Creating account…'); const response = await fetch('/api/admin/users', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); setMessage(response.ok ? `Account created. Temporary password: ${data.temporaryPassword}` : data.error); if (response.ok) { setForm({ ...form, fullName: '', email: '', password: '' }); await load() } }
  async function toggle(user: Staff) { await supabase.rpc('set_user_suspension', { p_user_id: user.id, p_suspended: !user.is_suspended }); await load() }
  return <main className="min-h-screen bg-background px-6 py-10"><div className="mx-auto max-w-5xl space-y-8"><header><p className="font-mono text-xs uppercase tracking-[0.25em] text-primary">{role === 'super_admin' ? 'Platform control' : 'Campus control'}</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">Staff accounts</h1><p className="mt-2 text-muted-foreground">Create verified admin and worker accounts. Public signup remains student-only.</p></header><form onSubmit={createStaff} className="grid gap-4 rounded-3xl border border-border bg-card p-6 md:grid-cols-2"><input required placeholder="Full name" value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} className="rounded-xl border border-input bg-background px-4 py-3" /><input required type="email" placeholder="Work email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className="rounded-xl border border-input bg-background px-4 py-3" /><input type="password" placeholder="Temporary password (optional)" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} className="rounded-xl border border-input bg-background px-4 py-3" /><select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })} className="rounded-xl border border-input bg-background px-4 py-3"><option value="worker">Worker</option>{role === 'super_admin' && <option value="admin">Admin</option>}</select>{role === 'super_admin' && <select required value={form.collegeId} onChange={e => setForm({ ...form, collegeId: e.target.value })} className="rounded-xl border border-input bg-background px-4 py-3"><option value="">Select college</option>{colleges.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select>}<button className="rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground">Create staff login</button>{message && <p className="md:col-span-2 text-sm text-muted-foreground">{message}</p>}</form><section className="rounded-3xl border border-border bg-card p-6"><h2 className="text-xl font-semibold">Existing accounts</h2><div className="mt-4 divide-y divide-border">{staff.map(member => <div key={member.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-semibold">{member.full_name}</p><p className="text-sm text-muted-foreground">{member.role} · {member.is_suspended ? 'Suspended' : 'Active'}</p></div><button onClick={() => toggle(member)} className="rounded-lg border border-border px-3 py-2 text-sm">{member.is_suspended ? 'Restore' : 'Suspend'}</button></div>)}</div></section></div></main>
}
